apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy-scraper.yaml
- deploy-triage.yaml
- pvc-cache.yaml
- pvc-output.yaml
- route.yaml
- service-scraper.yaml
- service-triage.yaml
images:
- digest: sha256:3bd4b10adaa28df6d445e6e777b02695b6f9a2248bcb6cd46ce83f3832a8a134
  name: quay.io/rh-obulatov/triage
